### ISSUE TITLE
[mobile] Short body makes menu animation look odd

### ISSUE THREAD

**Issue by pitaj** [NodeBB/nodebb-theme-persona#183]
When the body does not cover the whole viewport, the menu animation is super weird. Here's a screenshot:

![huh](http://i.imgur.com/6APWDQm.png)

Yeah, so this is a thing. I think this would fix it:

```css
 body {
   min-height: 100%;
 }
```
Alternatively use `vh` units
