### ISSUE TITLE
pagination block invisible with Cosmo skin

### ISSUE THREAD

**Issue by joolswills** [NodeBB/nodebb-theme-persona#301]
Apologies if this is the wrong place to post - Wasn't sure if it should be here or under the nodebb repo.

I am using the Persona theme with the Cosmo skin on nodebb 1.0.3

The text colour on the pagination block is the same as the background so it is invisible. I added this to my custom css to fix

``` css
.pagination-block {
  color: #fff;   
}
```
