### ISSUE TITLE
Title is hard to read with a dark skin

### ISSUE THREAD

**Issue by shileiyu** [NodeBB/nodebb-theme-persona#352]
This style made title hard to read with a dark skin. Is it possible to make the style more adaptive with dark skin?
```less
.category > ul > li h2 a {
  color: @gray;
}
```
